import { defaultRules, SCALE } from './constants.js';

export const game = {
  state: 'start',
  gameMode: 'pvp', // 'pvp' for Player vs Player, 'pvc' for Player vs Computer
  weapon1: 'sword',
  weapon2: 'sword',
  ability1: null,
  ability2: null,
  rules: { ...defaultRules },
  weaponStats: {
    sword: { length: 50 * SCALE, width: 12 * SCALE, speed: 10 },
    spear: { length: 95 * SCALE, width: 10 * SCALE, speed: 8 },
    unarmed: { length: 0, width: 0, speed: 15 },
  },
  p1: {
    x: 100 * SCALE,
    y: 200 * SCALE,
    r: 25 * SCALE,
    vx: 0,
    vy: 0,
    speed: 5.5,
    angle: Math.random() * Math.PI * 2,
    rotSpeed: 0,
    hp: 100,
    mult: 1.0,
    white: 0,
    impactCd: 0,
    shieldAct: 0,
    shieldCd: 0,
    boostAct: 0,
    boostCd: 0,
    chaseCd: 0,
    fleeCd: 0,
    dashAct: 0,
    dashCd: 0,
    dashDmg: false,
    m1x: null,
    m1y: null,
    m1cd: 0,
    m2x: null,
    m2y: null,
    m2cd: 0,
    unarmedHits: 0,
  },
  p2: {
    x: 300 * SCALE,
    y: 200 * SCALE,
    r: 25 * SCALE,
    vx: 0,
    vy: 0,
    speed: 5.5,
    angle: Math.random() * Math.PI * 2,
    rotSpeed: 0,
    hp: 100,
    mult: 1.0,
    white: 0,
    impactCd: 0,
    shieldAct: 0,
    shieldCd: 0,
    boostAct: 0,
    boostCd: 0,
    chaseCd: 0,
    fleeCd: 0,
    dashAct: 0,
    dashCd: 0,
    dashDmg: false,
    m1x: null,
    m1y: null,
    m1cd: 0,
    m2x: null,
    m2y: null,
    m2cd: 0,
    unarmedHits: 0,
  },
  s1x: 0,
  s1y: 0,
  s2x: 0,
  s2y: 0,
  slowTimer: 0,
  swordCd: 0,
  started: false,
  winner: null,
  editingRule: null,
  inputValue: '',
};